name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  close-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.id != github.event.repository.owner.id
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "This repository is not accepting pull requests."
